//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBidding
    {
        public int recNo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string AuctionId { get; set; }
        public string BiddersId { get; set; }
        public Nullable<decimal> BidPrice { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
