//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBranchShop
    {
        public int recNo { get; set; }
        public string BranchId { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string BranchContactNo { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
