//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAuctionProduct
    {
        public Nullable<long> rowNum { get; set; }
        public int recNo { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string CategoryName { get; set; }
        public string ProductId { get; set; }
        public Nullable<double> AskPrice { get; set; }
        public Nullable<System.DateTime> DateTimeLimit { get; set; }
        public Nullable<int> Status { get; set; }
        public string WinnerName { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> totalProductSold { get; set; }
    }
}
